services:
  - docker

before_install:
- docker pull registry:latest

script:
- docker login -u chenpengfei -p 1107100226fly
- docker tag registry:latest  chenpengfei/registry:latest
- docker push  chenpengfei/registry:latest
