services:
  - docker
  - command: ["--insecure-registry=http://172.168.200.37:10000"]
before_install:
- docker pull registry:latest

script:
- docker login -u chenpengfei  -p  pass4W0rd@  http://183.237.235.178:10000
- docker tag registry:latest  183.237.235.178:10000/cfss/registry:test
- docker push  183.237.235.178:10000/cfss/registry:test
