services:
  - docker
before_install:
- docker pull  gcr.io/kubernetes-e2e-test-images/resource-consumer:1.3

script:
#- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-hangzhou.aliyuncs.com
- docker login -u $DOCKER_USERNAME_DOCKERHUB -p $DOCKER_PASSWORD_DOCKERHUB
- docker tag gcr.io/kubernetes-e2e-test-images/resource-consumer:1.3  chenpengfei/resource-consumer:1.3
- docker push  chenpengfei/resource-consumer:1.3

